// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Chirp struct {
	ID        int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Body      string
	UserID    int32
}

type User struct {
	ID        int32
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
